name: Format

on:
  # code review question: this commits directly to PR branches.
  # that seems like what we're looking for, but we could also format only
  # committed code.
  pull_request:
    branches:
      - main

# cancels in-progress jobs on this pull request
# avoids wasted work when a new commit is pushed
concurrency:
  group: format-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          java-version: '11.0.10'
          distribution: 'zulu'

      - id: file_changes
        uses: tj-actions/changed-files@79adacd43ea069e57037edc891ea8d33013bc3da # v35.7.11
        with:
          json: 'true'

      - uses: axel-op/googlejavaformat-action@dbff853fb823671ec5781365233bf86543b13215 # v3
        with:
          version: 1.9
          skip-commit: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: show diff
        run: git add .; git diff --exit-code HEAD

      - name: Run npm install
        run: >
          cp formatter/package*.json . &&
          npm install &&
          rm package*.json

      - name: Prettier diff
        uses: actionsx/prettier@e90ec5455552f0f640781bdd5f5d2415acb52f1a
        with:
          # prettier CLI arguments.
          args: --check .

      - name: Run ESLint on browser tests
        working-directory: browser-test
        run: npm install && npx eslint . --ext .ts

      - name: Run ESLint on server
        working-directory: server
        run: npm install && npx eslint . --ext .ts

      - name: show diff
        run: git add .; git diff --exit-code HEAD

      - name: Check bin scripts have docstrings.
        if: contains(toJSON(steps.file_changes.outputs.all_changed_files), 'bin/') || contains(toJSON(steps.file_changes.outputs.all_changed_files), '.github/workflows/format.yaml')
        id: check_bin_script_docs
        run: bin/help

      - name: Run validate_java_classes_marked_final
        run: bin/validate_java_classes_marked_final
      - name: show bin/validate_java_classes_marked_final diff
        run: git add .; git diff --exit-code HEAD

  formatter-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0 # get main
      - id: file_changes
        uses: tj-actions/changed-files@79adacd43ea069e57037edc891ea8d33013bc3da # v35.7.11
        with:
          json: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0
      - name: Build formatter
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
        with:
          file: formatter/formatter.Dockerfile
          load: true
          push: false
          tags: civiform/formatter
          cache-from: |
            civiform/formatter:latest
      - name: Run Browsertest formatter
        if: contains(toJSON(steps.file_changes.outputs.all_changed_files), 'browser-test/') || contains(toJSON(steps.file_changes.outputs.all_changed_files), '.github/workflows/format.yaml') || contains(toJSON(steps.file_changes.outputs.all_changed_files), 'formatter')
        run: browser-test/bin/fmt
      - name: show Browsertest diff
        run: git add .; git diff --exit-code HEAD
      - name: run bin/fmt
        run: bin/fmt
      - name: show bin/fmt diff
        run: git add .; git diff --exit-code HEAD

  scala-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0 # get main
      - id: file_changes
        uses: tj-actions/changed-files@79adacd43ea069e57037edc891ea8d33013bc3da # v35.7.11
        with:
          json: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2.5.0
      - name: Run bin/fmt-sbt
        env:
          DOCKER_BUILDKIT: 1
        if: contains(toJSON(steps.file_changes.outputs.all_changed_files), '.sbt') || contains(toJSON(steps.file_changes.outputs.all_changed_files), '.scala') || contains(toJSON(steps.file_changes.outputs.all_changed_files), '.github/workflows/format.yaml') || contains(toJSON(steps.file_changes.outputs.all_changed_files), 'fmt-sbt')
        run: bin/fmt-sbt
      - name: show bin/fmt-sbt diff
        run: git add .; git diff --exit-code HEAD

  shell-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Run the shell checker
        uses: luizm/action-sh-checker@76ab0b22e1f194e4a582edc7969df6485c4e9246 # master
        env:
          SHELLCHECK_OPTS: -s bash -S error
          sh_checker_exclude: '*.md'
          SHFMT_OPTS:
            -bn -ci -i 2
            # -i 2   indent 2 spaces
            # -bn    binary ops like && and | may start a line
            # -ci    switch cases will be indented

  python-formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: run YAPF to test if python code is correctly formatted
        uses: AlexanderMelde/yapf-action@a2053dba9adceb173b38e58acaad7436a1934bdd # v1.0
        with:
          args: "--verbose --style='{based_on_style: google, SPLIT_BEFORE_FIRST_ARGUMENT:true}'"
