name: pr_env_var_docs

# Cancels in-progress jobs on this pull request when new commits are pushed.
# This avoids wasted work for old commits.
concurrency:
  group: pr-env-var-docs-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'env-var-docs/**'
      - 'server/conf/env-var-docs.json'
      - 'server/conf/application.conf'
      - 'server/conf/helper/*.conf'
      - '.github/workflows/pr_env_var_docs.yaml'

permissions:
  contents: read

jobs:
  run-validations:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: bin/env-var-docs-create-venv

      - name: Run tests
        run: bin/env-var-docs-run-tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3.1.1
        with:
          verbose: true
          files: coverage.xml
          # We're getting intermittent issues with codecov trying to upload lately
          # disabling it from failing the entire pipeline for now.
          fail_ci_if_error: false

      - name: Check environment variables
        run: bin/env-var-docs-check-vars
