name: Create release

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The commit SHA on main for this release'
        required: true

      release_number:
        description: 'The number for this release e.g. v1.2.3'
        required: true

permissions:
  pull-requests: read

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run bin/create-release
        run: 'GH_TOKEN=${{ secrets.GITHUB_TOKEN }} bin/create-release ${{ github.event.inputs.commit_sha }} ${{ github.event.inputs.release_number }}'

  update_environment_variable_documentation_markdown:
    needs: create_release # The generate markdown job relies on the release tag being added, so wait for bin/create-release to complete.
    uses: ./.github/workflows/generate_env_var_docs_markdown_for_release.yaml
    with:
      release_number: ${{ github.event.inputs.release_number }}
    secrets:
      CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN: ${{ secrets.CIVIFORM_GITHUB_AUTOMATION_PERSONAL_ACCESS_TOKEN }}
